---
title: "Parsing the Phenotype Data"
author: "Ashton Omdahl"
editor: "Shun Sambongi"
output: html_document
---


## Load the relevant libraries  
```{r}
source('shun.r')
use.package("readr")
use.package("tidyr")
use.package("dplyr")
use.package("ggplot2")
```

##Import the data, keep just what we are interested in
```{r}
phenoRaw <- import.data("BRCA_clinicalMatrix")

phenoCore <- phenoRaw %>% 
  select(sampleID, age_at_initial_pathologic_diagnosis, days_to_death, gender, PAM50Call_RNAseq,breast_carcinoma_estrogen_receptor_status, histological_type, tumor_tissue_site, vital_status) %>%
  filter(age_at_initial_pathologic_diagnosis < 80) %>% mutate(living=vital_status=="LIVING")
```

Calculate the summary statistics of interest
```{r}
meanAgeAtDiagnosis <- mean(na.omit(phenoCore$age_at_initial_pathologic_diagnosis))
meanDaysTillDeath <- mean(na.omit(phenoCore$days_to_death))
numberOfPatients <- dim(phenoCore)[1]

#Different cancer types
byType <- phenoCore %>% count(PAM50Call_RNAseq)

#put this into a bar graph
ggplot(data = byType, mapping = aes(x= PAM50Call_RNAseq, y = n)) + 
  geom_bar(stat='identity', aes(fill=byType$PAM50Call_RNAseq)) + 
  ylab("Patient Count") + 
  xlab("Subtype Designation") + 
  theme(legend.position = "none")

save.figure("subtypes.png")
```

Load mutation data
```{r}
mutations <- import.data("mutation_curated_wustl_gene")
tp53 <- mutations %>% filter(sample == "TP53")
n <- tp53$sample
tp53.t <- as.data.frame(t(tp53[,-1]))
colnames(tp53.t) <- n
tp53.pos <- tp53.t[tp53.t$TP53 == 1,,drop=FALSE]
tp53.samples <- rownames(tp53.pos)
```


Tinkering with survival data
```{r}
use.package("survival")
TP53.survival <- Surv(phenoCore$days_to_death, phenoCore$living)
summary(survfit(TP53))

```
